"""Deploy artifact templates and their render functions.

Templates are plain strings rendered with ``string.Template`` —
audit-transparent, no template-engine dependency, no package data to
ship. Placeholders are lowercase (``$port``, ``$agent_ref``); uppercase
shell variables (``$PORT``, ``$AGENT_REF``) and Go-template braces pass
through untouched because rendering uses ``safe_substitute``.

This module holds the container artifacts (Dockerfile, ``.dockerignore``,
a starter ``requirements.txt``). Orchestration/IaC manifests live beside
them as the matching targets are added.
"""

from __future__ import annotations

from string import Template
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from philharmonica.adk.deploy.context import DeployContext

DOCKERFILE_TEMPLATE = Template(
    """\
# Generated by `philharmonica deploy`. The image satisfies the universal
# container contract: it binds 0.0.0.0 on $PORT, takes config from env,
# runs non-root, and starts fast. The ASGI runtime (uvicorn) runs the
# agent; nothing in the image owns runtime state.
FROM python:$python_version-slim

ENV PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1 \\
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

# Install dependencies first for layer caching. requirements.txt resolves
# philharmonica-adk[$extras] from PyPI by default; swap in a pin, a vendored
# wheel, or a VCS URL there if the build must not reach PyPI. Add your
# agent's own dependencies to the same file.
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Run as a non-root user.
RUN adduser --disabled-password --gecos "" appuser \\
    && chown -R appuser:appuser /app
COPY . .
USER appuser

ENV PORT=$port \\
    AGENT_REF=$agent_ref
EXPOSE $port

# Bind all interfaces and honor the platform-injected $PORT (Cloud Run,
# Knative, and App Runner all set it).
CMD ["sh", "-c", "philharmonica serve --agent \\"$AGENT_REF\\" --host 0.0.0.0 --port \\"$PORT\\""]
"""
)

DOCKERIGNORE = """\
.git
.gitignore
.dockerignore
Dockerfile
__pycache__/
*.py[cod]
.venv/
venv/
.env
.env.*
*.db
*.sqlite
.coverage/
.pytest_cache/
.mypy_cache/
.ruff_cache/
dist/
build/
*.egg-info/
.augments/
"""

REQUIREMENTS_TEMPLATE = Template(
    """\
# philharmonica-adk resolves from PyPI. Add your agent's own dependencies
# below. Replace the line below if the build must not reach PyPI:
#   pinned:         philharmonica-adk[$extras]==<version>
#   private index:  add `--extra-index-url https://<your-index>/simple` here
#   vendored wheel: drop the wheel in the build context and reference its path
#   VCS install:    philharmonica-adk[$extras] @ git+https://<your-repo>
philharmonica-adk[$extras]
"""
)


def render_dockerfile(ctx: DeployContext) -> str:
    """Render the Dockerfile for *ctx*.

    Args:
        ctx: The deploy context.

    Returns:
        The Dockerfile contents.
    """
    return DOCKERFILE_TEMPLATE.safe_substitute(
        python_version=ctx.python_version,
        extras=ctx.extras,
        port=ctx.port,
        agent_ref=ctx.agent_ref,
    )


def render_dockerignore() -> str:
    """Return the ``.dockerignore`` contents (static)."""
    return DOCKERIGNORE


def render_requirements(ctx: DeployContext) -> str:
    """Render a starter ``requirements.txt`` for *ctx*.

    Args:
        ctx: The deploy context.

    Returns:
        The ``requirements.txt`` contents.
    """
    return REQUIREMENTS_TEMPLATE.safe_substitute(extras=ctx.extras)
